-- Insert sample T-Shirt products into the products table
INSERT INTO public.products (name, description, category, base_price, images, sizes, frames, is_customizable, is_active) VALUES
('Round Neck T-Shirt', 'Premium cotton round neck t-shirt perfect for custom printing', 'tshirts', 399, ARRAY['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Polo T-Shirt', 'Classic polo t-shirt with collar for a professional look', 'tshirts', 599, ARRAY['https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('V-Neck T-Shirt', 'Stylish V-neck design for a modern casual look', 'tshirts', 449, ARRAY['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Full Sleeve T-Shirt', 'Comfortable full sleeve t-shirt for all seasons', 'tshirts', 549, ARRAY['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Oversized T-Shirt', 'Trendy oversized fit for a relaxed street style', 'tshirts', 649, ARRAY['https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Sports Dry-Fit T-Shirt', 'Moisture-wicking fabric ideal for sports and workouts', 'tshirts', 699, ARRAY['https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Corporate Event T-Shirt', 'Bulk order friendly t-shirt for corporate events', 'tshirts', 349, ARRAY['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true),
('Premium Cotton T-Shirt', 'Extra soft 100% cotton for ultimate comfort', 'tshirts', 799, ARRAY['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop'], '[{"name": "S", "price": 0}, {"name": "M", "price": 0}, {"name": "L", "price": 50}, {"name": "XL", "price": 50}, {"name": "XXL", "price": 100}]'::jsonb, '[]'::jsonb, true, true);