// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqnknqgpqttjqqhaejmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbmtucWdwcXR0anFxaGFlam10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDU1MjgsImV4cCI6MjA4MDE4MTUyOH0.7CqCyiGUFb1sHN5wwE8rtULbTKNA0Dfj6X_do5VDy1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});